#!/bin/bash
#The partition is the queue you want to run on. standard is gpu and can be ommitted.
#SBATCH -p gpu
#SBATCH --job-name=test_qa
#number of independent tasks we are going to start in this script
#SBATCH --output=results.out   # %j will be replaced with the job ID
#SBATCH --ntasks=1 
#number of cpus we want to allocate for each program
#SBATCH --cpus-per-task=1
#SBATCH --gres=gpu:a40:1
#Note that a program will be killed once it exceeds this time!
#SBATCH --time=0-3:00:00
#Skipping many options! see man sbatch
# From here on, we can start our program

# Load python
module load python/3.9.6

# Activate the virtual environment
source production_env/bin/activate

# Run program 
python3 -u -m scripts.generalized.evaluate --config configs/generalized/qa_with_squad_no_context.yaml
python3 -u -m scripts.generalized.evaluate --config configs/generalized/qa_with_squad_contexts.yaml
python3 -u -m scripts.generalized.evaluate --config configs/generalized/qa_with_wiki.yaml
python3 -u -m scripts.generalized.evaluate --config configs/generalized/qa_with_squad_rewritten.yaml
python3 -u -m scripts.generalized.evaluate --config configs/generalized/qa_with_squad_rewritten_wiki.yaml


