questions_path: data/squad/dev-v1.1-da.json
question_type: squad
kb_path: data/wiki/chunked/ # path to knowledge base
kb_type: wiki
index_path: data/wiki/index/index.faiss
retriever_name: e5
device: cuda
save_path: results/squad/qa_with_wiki_contexts
generator_name: nous-hermes-mistral
n_questions: 100
batch_size: 8
