questions_path: data/squad/dev-v1.1-da.json
question_type: squad
kb_path: data/wiki/chunked/ # path to knowledge base
kb_type: wiki
index_path: data/wiki/index/index.faiss
retriever_name: e5
device: cuda
save_path: results/squad/qa_with_wiki_contexts
generator_name: nous-hermes-mistral
n_questions: 2000
batch_size: 8
pipeline: test_qa_with_retrieval_wiki

# for evaluation 
answers_path: results/squad/qa_with_wiki_contexts
evaluator_name: nous-hermes-mistral-binary
evaluation_path: results/squad/evaluation_with_wiki_contexts