documents_path:  
index_path: /dtu/p1/oscrev/synthetic/index_E5_epoch3
embedder_name: e5
device: cuda
retriever_name: e5-gpu
save_path: results/synthetic/results_E5_epoch3
batch_size: 2048
max_samples: 
test: True
overwrite: True