documents_path: 
index_path: /dtu/p1/oscrev/synthetic/index_E5_finetuned_full
embedder_name: e5-finetuned
device: cuda
retriever_name: e5-gpu
save_path: results/synthetic/results_E5_finetuned_full_1000
batch_size: 2048
max_samples: 
test: True