documents_path:  
index_path: /dtu/p1/oscrev/synthetic/index_E5_finetuned
embedder_name: e5-finetuned
device: cuda
retriever_name: e5-finetuned
save_path: results/synthetic/results_E5_finetuned
batch_size: 2048
max_samples: 
test: True