#!/bin/bash
### General options 
### -- specify queue -- 
#BSUB -q p1
### -- set the job Name -- 
#BSUB -J test_retrieval_news
### -- ask for number of cores (default: 1) -- 
#BSUB -n 1
### -- specify that the cores must be on the same host -- 
#BSUB -R "span[hosts=1]"
### -- specify that we need 4GB of memory per core/slot -- 
#BSUB -R "rusage[mem=20GB]"
### -- specify that we want the job to get killed if it exceeds 5 GB per core/slot -- 
#BSUB -M 20GB 
### -- set walltime limit: hh:mm -- 
#BSUB -W 1:30
###BSUB -u krf217@alumni.ku.dk
### -- send notification at start -- 
###BSUB -B 
### -- send notification at completion -- 
###BSUB -N 
### -- Specify the output and error file. %J is the job-id -- 
### -- -o and -e mean append, -oo and -eo mean overwrite -- 
#BSUB -oo Output.out 
#BSUB -eo Output.err 

# here follow the commands you want to execute with input.in as the input file

# set up conda venv
source ~/miniconda3/etc/profile.d/conda.sh
conda activate production_env
export LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH

# set config path
yaml=configs/citizenship/test_e5/test_regular.yaml

# build index
# python3 -u -m scripts.wiki.build_index --config $yaml

# run qa for multiple values of k retrieval
python3 -u -m scripts.generalized.qa_multiple --config $yaml

# evaluate every answer 
python3 -u -m scripts.experiments.test_evaluate --config $yaml

# score all answers
python3 -u -m scripts.experiments.test_score --config $yaml



