questions_path: 
question_type: citizenship
kb_path: /dtu/p1/oscrev/wiki/chunked_paragraph # path to knowledge base
kb_type: wiki
index_path: /dtu/p1/oscrev/wiki/index/index_e5_finetuned
retriever_name: e5-finetuned
device: cuda
save_path: results/citizenship/gemma_finetuned
generator_name: gemma-9b
n_questions: 
batch_size: 8
pipeline: test_qa_citizenship

# for evaluation 
answers_path: results/citizenship/gemma_finetuned
evaluator_name: gemma-9b-binary
evaluation_type: binary
evaluation_path: results/citizenship/evaluation_gemma_finetuned