questions_path: 
question_type: citizenship
kb_path: # path to knowledge base
kb_type: 
index_path: data/wiki/index/index.faiss
retriever_name: e5
device: cuda
save_path: results/citizenship/gemma_no_context_mc
generator_name: gemma-9b
n_questions: 
batch_size: 8
pipeline: qa_citizenship_mc_no_context

# for evaluation 
answers_path: results/citizenship/gemma_no_context_mc
evaluator_name: nous-hermes-mistral-binary
evaluation_type: multiple_choice
evaluation_path: results/citizenship/gemma_no_context_mc