questions_path: 
question_type: citizenship
kb_path: /dtu/p1/oscrev/wiki/chunked_paragraph # path to knowledge base
kb_type: wiki
index_path: /dtu/p1/oscrev/wiki/index/index_paragraph
retriever_name: e5
device: cuda
save_path: results/citizenship/gemma_wiki_mc
generator_name: gemma-9b
n_questions: 
batch_size: 32
pipeline: qa_news_mc

# for evaluation 
answers_path: results/citizenship/gemma_wiki_mc
evaluator_name: gemma-9b-binary
evaluation_type: multiple_choice
evaluation_path: results/citizenship/gemma_wiki_mc