questions_path: 
question_type: citizenship
kb_path: /dtu/p1/oscrev/wiki/chunked_paragraph # path to knowledge base
kb_type: wiki
index_path: /dtu/p1/oscrev/wiki/index/bm25_paragraph
retriever_name: bm25-sparse
device: cuda
save_path: results/citizenship/gemma_wiki_bm25_test
generator_name: gemma-9b
n_questions: 
batch_size: 8
pipeline: test_qa_citizenship

# for evaluation 
answers_path: results/citizenship/gemma_wiki_bm25_test
evaluator_name: nous-hermes-mistral-binary
evaluation_type: binary
evaluation_path: results/citizenship/evaluation_gemma_wiki_bm25_test