questions_path: 
question_type: citizenship
kb_path: data/wiki/chunked/ # path to knowledge base
kb_type: wiki
index_path: data/wiki/index/index.faiss
retriever_name: e5
device: cuda
save_path: results/citizenship/qa_with_wiki
generator_name: nous-hermes-mistral
n_questions: 
batch_size: 8
pipeline: test_qa_citizenship

# for evaluation 
answers_path: results/citizenship/qa_with_wiki
evaluator_name: nous-hermes-mistral-binary
evaluation_path: results/citizenship/evaluation_with_wiki_contexts