#!/bin/bash
### General options 
### -- specify queue -- 
#BSUB -q p1
### -- set the job Name -- 
#BSUB -J train_e5
### -- ask for number of cores (default: 1) -- 
#BSUB -n 8
#BSUB -gpu "num=2"
### -- specify that the cores must be on the same host -- 
#BSUB -R "span[hosts=1]"
### -- specify that we need 4GB of memory per core/slot -- 
#BSUB -R "rusage[mem=80GB]"
### -- specify that we want the job to get killed if it exceeds 5 GB per core/slot -- 
#BSUB -M 80GB
### -- set walltime limit: hh:mm -- 
#BSUB -W 1:00
##BSUB -u krf217@ku.dk
### -- send notification at start -- 
##BSUB -B 
### -- send notification at completion -- 
##BSUB -N 
### -- Specify the output and error file. %J is the job-id -- 
### -- -o and -e mean append, -oo and -eo mean overwrite -- 
#BSUB -oo logs/train.out 
#BSUB -eo logs/train.err 

# here follow the commands you want to execute with input.in as the input file
source ~/miniconda3/etc/profile.d/conda.sh
conda activate production_env
export LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH

python3 -u -m scripts.training.train_e5
