documents_path: data/news/2025/articles.json
questions_path: data/news/2025/questions.jsonl
chunked_path: data/news/2025/chunked_articles.json
index_path: data/news/2025/index.faiss
tokenizer_name: intfloat/multilingual-e5-large-instruct
embedder_name: e5
retriever_name: e5
retrieval_save_path: results/retrieval_2025
qa_save_path: results/qa_2025
device: cuda
generator_name: nous-hermes-mistral
