#!/bin/bash
#SBATCH -p gpu
#SBATCH --job-name=sanity_test
#SBATCH --output=results.out
#SBATCH --ntasks=1
#SBATCH --time=0-00:01:00
#SBATCH --gres=gpu:titanrtx:1


echo "SLURM is working!"
hostname
nvidia-smi
