questions_path: 
question_type: citizenship
kb_path: /dtu/p1/oscrev/wiki/chunked_paragraph # path to knowledge base
kb_type: wiki
index_path: /dtu/p1/oscrev/wiki/index/index_paragraph
retriever_name: e5
device: cuda
save_path: results/citizenship/gemma_wiki_paragraph
generator_name: gemma-9b
n_questions: 
batch_size: 8
pipeline: test_cfg
