questions_path: /dtu/p1/oscrev/news/2025/questions.jsonl
question_type: news
kb_path: /dtu/p1/oscrev/news/2025/chunked_paragraph.jsonl # path to knowledge base
kb_type: news
index_path: /dtu/p1/oscrev/news/2025/index_paragraph
retriever_name: e5
device: cuda
save_path: results/news/e5_top1
generator_name: gemma-9b
n_questions: 32
batch_size: 32
pipeline: test_qa_with_retrieval
top_k: 1

# for evaluation 
answers_path: results/news/e5_top1
evaluator_name: gemma-9b-binary
evaluation_path: results/news/evaluation_e5_top1
evaluation_type: binary