questions_path: data/custom/valde_question
question_type: custom
kb_path: /dtu/p1/oscrev/wiki/chunked_paragraph # path to knowledge base
kb_type: wiki
index_path: /dtu/p1/oscrev/wiki/index/index_paragraph
retriever_name: e5
device: cuda
save_path: results/custom/valde_question
generator_name: gemma-9b
n_questions: 
batch_size: 8
pipeline: test_qa_with_retrieval

# for evaluation 
answers_path: results/custom/valde_question
evaluator_name: gemma-9b-binary
evaluation_type: binary
evaluation_path: results/custom/evaluation_valde_question