documents_path: data/news/scraped_articles_week1_2025.json
questions_path: data/news/questions_week1_2025.jsonl
index_path: data/news/index.faiss
retriever_name: gpt2
save_path: results/qa_with_retrieval_news_week1_2025
device: cuda
generator_name: gpt2
