questions_path: 
question_type: mkqa
kb_path: # path to knowledge base
kb_type:
index_path: /dtu/p1/oscrev/wiki/index/index_paragraph
retriever_name: e5
device: cuda
save_path: results/mkqa/gemma_no_context
generator_name: gemma-9b
n_questions: 
batch_size: 32
pipeline: test_qa_no_context

# for evaluation 
answers_path: results/mkqa/gemma_no_context
evaluator_name: gemma-9b-binary
evaluation_type: binary
evaluation_path: results/mkqa/evaluation_gemma_no_context