questions_path: 
question_type: mkqa
kb_path: /dtu/p1/oscrev/wiki/chunked_paragraph # path to knowledge base
kb_type: wiki
index_path: /dtu/p1/oscrev/wiki/index/index_paragraph
retriever_name: e5
device: cuda
save_path: results/mkqa/gemma_with_context
generator_name: gemma-9b
n_questions: 
batch_size: 32
pipeline: test_qa_citizenship

# for evaluation 
answers_path: results/mkqa/gemma_with_context
evaluator_name: gemma-9b-binary
evaluation_type: binary
evaluation_path: results/mkqa/evaluation_gemma_with_context