documents_path: /dtu/p1/oscrev/webfaq_danish
index_path: /dtu/p1/oscrev/webfaq/index_E5_finetuned
embedder_name: e5-local
device: cuda
retriever_name: e5_gpu
save_path: results/webfaq/results_E5_finetuned
batch_size: 2048