documents_path: /dtu/p1/oscrev/webfaq_danish
index_path: /dtu/p1/oscrev/webfaq/index_E5_epoch8
embedder_name: e5-large
device: cuda
retriever_name: e5-gpu
save_path: results/webfaq/results_E5_epoch8
batch_size: 2048
max_samples: 
test: True
overwrite: True