documents_path: /dtu/p1/oscrev/webfaq_danish
index_path: /dtu/p1/oscrev/webfaq/index_E5_epoch2
embedder_name: e5-finetuned
device: cuda
retriever_name: e5-gpu
save_path:  
batch_size: 2048
max_samples: 
test: True
overwrite: False