documents_path: data/wiki/wiki_00
tokenizer_name: intfloat/multilingual-e5-large-instruct
chunked_path: data/wiki/chunked
embedder_name: bert-tiny
index_path: data/wiki/index/index.faiss
retriever_name: dummy
device: mps
dump_path: data/wiki/dump
questions_path: data/news/week1_2025/questions.jsonl
retrieval_save_path: results/wiki/retrieval_test