documents_path: data/wiki/wiki_00
tokenizer_name: intfloat/multilingual-e5-large-instruct
chunked_path: data/wiki/chunked
embedder_name: e5
index_path: data/wiki/index/index.faiss
retriever_name: e5
device: cuda
dump_path: data/wiki/dump/
questions_path: data/squad/rewritten/test.json
retrieval_save_path: results/wiki/retrieval_test_rewritten
batch_size: 2048
qa_save_path: results/wiki/qa_test_rewritten
n_questions: 1000
generator_name: nous-hermes-mistral
evaluator_name: nous-hermes-mistral-binary
eval_batch_size: 16
answers_path: results/wiki/qa_test_rewritten
evaluation_path: results/wiki/evaluation_test_rewritten
squad_questions_with_title: False