squad_path: data/squad/dev-v1.1-da.json
squad_context_path: data/squad/context/contexts.json
embedder_name: e5
index_path: data/squad/context/index.faiss
retriever_name: e5
device: cuda
questions_path: data/squad/dev-v1.1-da.json
retrieval_save_path: results/squad/retrieval_test
n_questions: 1000
batch_size: 64
squad_questions_with_title: False