questions_path: 
question_type: citizenship
kb_path: /dtu/p1/oscrev/wiki/chunked_paragraph # path to knowledge base
kb_type: wiki
index_path: /dtu/p1/oscrev/wiki/index/index_paragraph
retriever_name: e5
device: cuda
save_path: results/citizenship/test_qa/
generator_name: gemma-9b
n_questions: 
batch_size: 32
top_k: 5

pipelines:
  top1: test_qa_with_retrieval
  top5: test_qa_with_retrieval
  top10: test_qa_with_retrieval
  top25: test_qa_with_retrieval


