questions_path: /dtu/p1/oscrev/news/2025/questions.jsonl
question_type: news
kb_path: /dtu/p1/oscrev/news/2025/chunked_no_title # path to knowledge base
kb_type: news
index_path: /dtu/p1/oscrev/news/2025/index_e5_finetuned_no_title
retriever_name: e5-finetuned
device: cuda
save_path: results/news/test_e5_finetuned_no_title/
directory: results/news/test_e5_finetuned_no_title/
generator_name: gemma-9b
n_questions: 16
batch_size: 16
pipeline: test_qa_with_retrieval
mc_pipeline : qa_news_mc

# for evaluation 
answers_path: results/news/qa_wiki_paragraph
evaluator_name: gemma-9b-binary
evaluation_type: binary

# for index building
documents_path: /dtu/p1/oscrev/news/2025/articles.json
chunked_path: /dtu/p1/oscrev/news/2025/chunked_no_title
splitter_name: paragraph
prepend_with_title: False

# for embedding 
embedder_name: e5-finetuned
device: cuda